apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23.azurecr.io/python-application-01
  digest: sha256:e240fb6f09645bb29d02b4a586e0361ed522c7af5d6a0d3e7ddfa008da3eb9f0
