apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23.azurecr.io/application-02
  digest: sha256:db6d94c42fe1f382ec161d5f591bed0e5fd6db4ee62e66db6dd2f1d15c65ba37
