apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23193.azurecr.io/application-02
  digest: sha256:3345af5bfd913f51a64977c7499ac5f3bd98774b5135aab21d6c560b9c72e11d
