apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23.azurecr.io/application-02
  digest: sha256:a56d7b71d69bfd85828531a1e2e10a3d428362bbec6eab656c87970345ecb324
