apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23.azurecr.io/java-application-03
  digest: sha256:fe02ecff95ba7b280d1d1b702529d1e145eb1b9a111507cd1174a65be72cac20
