apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23.azurecr.io/java-application-03
  digest: sha256:c3ba0700428742e0aa6520d95982c39f44ad3652a61bbe4f8c563538dbcda6f7
