apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23.azurecr.io/application-01
  digest: sha256:9626c125ce7f8ebdefd412c3a5fda78e52d6101d4820776b781fd12b4e2a61fc
