apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23.azurecr.io/application-01
  digest: sha256:d37944726a16204290bc13012c2ef9bbb62d4db775152e3df800140841ccbe52
