apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: samplez
spec:
  gateways:
    - default/main-gateway
  hosts:
    - '*'
  http:
  - match:
    - uri:
        prefix: /python-application-01
    route:
    - destination:
        host: python-application-01.samplez-ns-python.svc.cluster.local
        port:
          number: 8080