apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23193.azurecr.io/java-application-01
  digest: sha256:5676e5a783801104924f8ef55e0731a4a1e97add4d57291582da6e40fa817ea1
