apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sharedregistry23193.azurecr.io/java-application-02
  digest: sha256:9a77db6fcfaf8da4ff5c6f47311964131a9776400a4c8c096ba1c0c5a8b9453b
