apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: samplez
spec:
  http:
  - match:
    - uri:
        prefix: /java-application-03
    route:
    - destination:
        host: java-application-03.samplez-ns-java.svc.cluster.local
        port:
          number: 8080