kind: Deployment
apiVersion: apps/v1
metadata:
  name: samplez
  namespace: samplez
spec:
  template:
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: app
        image: sharedregistry23.azurecr.io/application-01:dev
