apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: samplez
spec:
  http:
  - match:
    - uri:
        prefix: /python-application-03
    route:
    - destination:
        host: python-application-03.samplez-ns-python.svc.cluster.local
        port:
          number: 8080